### ISSUE TITLE
一个需要校验的字段名可以同时校验多个正则吗？

### ISSUE THREAD

**Issue by zbth5** [lulei90/smart-validate#1]
现在碰到了如下问题：需要校验usename这个字段名，但是这个字段名的校验规则是手机号或者是身份证号，能否在自定义schame时，传入多个正则进行校验（不是同时满足两个正则而是满足其中一个就行了）

**Comment by lulei90** [comment]
校验规则可以传入函数，这种满足其中一种情况的可以使用自定义函数协助完成
